function hexToFlutter(hex) {
  return `Color(0xFF${hex.slice(1).toUpperCase()})`;
}

function hexToRgbaFlutter(hex, opacity) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const a = Math.round(opacity * 255);
  return `Color.fromRGBO(${r}, ${g}, ${b}, ${opacity})`;
}

export default function generateFlutter(s) {
  const lines = [];
  const ind = (n) => '  '.repeat(n);

  lines.push('// Generated by Button Constructor');
  lines.push('Container(');
  lines.push(`${ind(1)}width: ${s.btnWidth},`);
  lines.push(`${ind(1)}height: ${s.btnHeight},`);
  lines.push(`${ind(1)}decoration: BoxDecoration(`);
  lines.push(`${ind(2)}borderRadius: BorderRadius.circular(${s.borderRadius}),`);

  // Gradient (first body layer)
  const baseLayer = (s.bodyLayers || [])[0];
  if (baseLayer && baseLayer.type === 'gradient') {
    lines.push(`${ind(2)}gradient: LinearGradient(`);
    lines.push(`${ind(3)}begin: Alignment.topCenter,`);
    lines.push(`${ind(3)}end: Alignment.bottomCenter,`);
    lines.push(`${ind(3)}colors: [${baseLayer.gradColors.map(hexToFlutter).join(', ')}],`);
    lines.push(`${ind(3)}stops: [${baseLayer.gradStops.map((v) => (v / 100).toFixed(2)).join(', ')}],`);
    lines.push(`${ind(2)}),`);
  } else if (baseLayer && baseLayer.type === 'solid') {
    lines.push(`${ind(2)}color: ${hexToFlutter(baseLayer.color || '#ffffff')},`);
  }

  // Box shadows
  const shadows = [];
  if (s.depthOffset > 0) {
    shadows.push(
      `${ind(3)}BoxShadow(\n${ind(4)}color: ${hexToFlutter(s.depthColor)},\n${ind(4)}offset: Offset(0, ${s.depthOffset}),\n${ind(3)})`
    );
  }
  shadows.push(
    `${ind(3)}BoxShadow(\n${ind(4)}color: Color.fromRGBO(0, 0, 0, 0.25),\n${ind(4)}offset: Offset(0, ${s.depthOffset + 2}),\n${ind(4)}blurRadius: 4,\n${ind(3)})`
  );
  lines.push(`${ind(2)}boxShadow: [`);
  lines.push(shadows.join(',\n'));
  lines.push(`${ind(2)}],`);

  lines.push(`${ind(1)}),`);

  // Child Stack
  lines.push(`${ind(1)}child: Stack(`);
  lines.push(`${ind(2)}children: [`);

  // Shine
  if (s.showShine) {
    lines.push(`${ind(3)}// Shine overlay`);
    lines.push(`${ind(3)}Positioned(`);
    lines.push(`${ind(4)}top: 0, left: 4, right: 4,`);
    lines.push(`${ind(4)}height: ${Math.round(s.btnHeight * s.shineHeight / 100)},`);
    lines.push(`${ind(4)}child: Container(`);
    lines.push(`${ind(5)}decoration: BoxDecoration(`);
    lines.push(`${ind(6)}gradient: LinearGradient(`);
    lines.push(`${ind(7)}begin: Alignment.topCenter,`);
    lines.push(`${ind(7)}end: Alignment.bottomCenter,`);
    lines.push(`${ind(7)}colors: [Color.fromRGBO(255, 255, 255, ${s.shineOpacityTop}), Color.fromRGBO(255, 255, 255, 0)],`);
    lines.push(`${ind(6)}),`);
    lines.push(`${ind(5)}),`);
    lines.push(`${ind(4)}),`);
    lines.push(`${ind(3)}),`);
  }

  // Text
  if (s.showText) {
    lines.push(`${ind(3)}// Text`);
    lines.push(`${ind(3)}Center(`);
    lines.push(`${ind(4)}child: Text(`);
    lines.push(`${ind(5)}'${s.text}',`);
    lines.push(`${ind(5)}style: TextStyle(`);
    lines.push(`${ind(6)}fontFamily: 'Nunito',`);
    lines.push(`${ind(6)}fontWeight: FontWeight.w900,`);
    lines.push(`${ind(6)}fontSize: ${s.fontSize},`);
    lines.push(`${ind(6)}color: ${hexToFlutter(s.textColor)},`);
    lines.push(`${ind(5)}),`);
    lines.push(`${ind(4)}),`);
    lines.push(`${ind(3)}),`);
  }

  lines.push(`${ind(2)}],`);
  lines.push(`${ind(1)}),`);
  lines.push(')');

  return lines.join('\n');
}
